branches:
  only:
  - dev

language: python
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/download
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
sudo: false

notifications:
  email: false

python:
  - 3.4
before_install:
  - chmod +x deploy.sh
install:
  - git submodule update --init --recursive
  # Miniconda
  - echo 'List files from cached directories'
  - echo 'pip:'
  - ls $HOME/.cache/pip
  - echo 'download'
  - ls $HOME/download
  - pushd .
  - mkdir -p download
  - echo "Cached in $HOME/download :"
  - ls -l
  - echo
  - if [[ ! -f miniconda.sh ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh \
             -O miniconda.sh;
    fi
  - chmod +x miniconda.sh && ./miniconda.sh -b
  - cd ..
  - export PATH="$HOME/conda/bin:$PATH"
  - conda config --set always_yes yes
  - popd
  # - conda update -q conda  # Never again! Bring Aaron back!
  - conda install pyyaml  # Related to https://github.com/conda/conda/issues/3738
  - conda info -a
  - conda env create
  - export PATH="$HOME/conda/envs/blog/bin:$PATH"
  - conda list

script:
  - make html

after_success: ./deploy.sh
